[tool.poetry]
name = "pydantic-data-creator"
version = "0.1.0"
description = ""
authors = ["yukikotani231 <kotani-yuki231@g.ecc.u-tokyo.ac.jp>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
